'use strict'

const dbtype = global.dbtype;
const comp = global.comp;

module.exports = {
	title: "Allo Topup",
	autoid: true,

	variance: {
		"view" : {title:"AlloTopUp (View)"}
	},

	persistent: {
		'trn_allotopup' : {
			primarykeys: ['allotopup_id'],
			comment: 'Daftar Topup Allo',
			data: {
				allotopup_id: {text:'ID', type: dbtype.varchar(36)},
				
				site_id: {
					text: 'Site', type: dbtype.varchar(30), null:true, suppresslist: true, 
					options:{required:true,invalidMessage:'Site harus diisi', prompt:'-- PILIH --'},
					comp: comp.Combo({
						title: 'Pilih Site',
						api: 'ent/location/site/list',
						table: 'mst_site', 
						field_value: 'site_id', field_display: 'site_name', 
						onDataLoadingHandler: false,
						onDataLoadedHandler: false,
						onSelectingHandler: false,
						onSelectedHandler: true
					})				
				},
				allotopup_date: { text: 'Date', type: dbtype.date, null: false },

				allotopup_name: { text: 'Name', type: dbtype.varchar(64), null: true },
				allotopup_email: { text: 'Email', type: dbtype.varchar(128), null: true, suppresslist: true },
				allotopup_phone: { text: 'Phone', type: dbtype.varchar(64), null: true, suppresslist: true },

				allotopup_validr: { text: 'Value IDR', type: dbtype.decimal(14, 2), null: false, default: 0, options: { required: true } },

				allotopup_clientref: { 
					section: section.Begin('Status'),
					text: 'Client Ref', type: dbtype.varchar(64), null: true, unset:true, suppresslist: true, options: {disabled: true} },

				allotopup_txid: { text: 'TxId', type: dbtype.varchar(64), null: true, unset:true, suppresslist: true, options: {disabled: true} },
				allotopup_nonce: { text: 'Nonce', type: dbtype.varchar(64), null: true, unset:true, suppresslist: true, options: {disabled: true} },
				allotopup_timestamp: { text: 'TimeStamp', type: dbtype.varchar(64), null: true, unset:true, suppresslist: true, options: {disabled: true} },

				allotopup_barcode: { text: 'Barcode', type: dbtype.varchar(64), null: true, unset:true, suppresslist: true, options: {disabled: true} },
				allotopup_alloref: { text: 'Allo Ref', type: dbtype.varchar(64), null: true, unset:true, suppresslist: true, options: {disabled: true} },
				allotopup_status: { text: 'Status', type: dbtype.varchar(64), null: true, unset:true, suppresslist: true, options: {disabled: true} },
				allotopup_message: { text: 'Message', type: dbtype.varchar(64), null: true, unset:true, suppresslist: true, options: {disabled: true} },

				allotopup_isdone: { text: 'Done', type: dbtype.boolean, null: false, default: '0', suppresslist: false, unset:true, options: { disabled: true } },
				allotopup_isgen: { text: 'Generated', type: dbtype.boolean, null: false, default: '0', suppresslist: true, unset:true, options: { disabled: true } },
				allotopup_genby: { text: 'Generated By', type: dbtype.varchar(14), suppresslist: true, unset:true, options: { disabled: true }, hidden: true, lookup:'user' },
				allotopup_gendate: { 
					section: section.End(),
					text: 'Generated Date', type: dbtype.datetime, suppresslist: true, unset:true, comp: comp.Textbox(), options: { disabled: true } , hidden: true},

			},

			defaultsearch : ['allotopup_id', 'allotopup_ref'],
		}
	},

	schema: {
		title: "Allo Topup",
		header: 'trn_allotopup',
		detils: {
			'barcode' : {title:'Barcode', table:'trn_allotopup',  form: false, headerview: 'allotopup_id'},
		},
		xtions: {
			generate: {
				api: 'xtion-generate',
				buttonname: 'btn_generate',
				buttontext: 'Generate'
			},
		},		
	},


}

