<div id="pnl_schema3" style="display:none; flex-direction: column; align-items: flex-start">
	<div class="fgta-page-title">Konfigurasi Skema</div>
	<div class="namatoko">Nama Toko</div>



	<div style="display: flex">
		<div style="width: 140px; text-align: center">
		<div><img name="pnl_selectmodel-schema" schemaname="schema3" src="index.php/asset/etap/client/config/icons/schema3.svg" width="140" height="140" style="cursor: pointer"></div>
			<div style="text-align: center; font-weight: bold">Skema 3</div>
			<div style="margin-top: 10px; margin-bottom: 10px">
			Menggunakan Master detil untuk data header transaksi, detil item, 
			dam mendukung lebih dari satu cara pembayaran dalam suatu transaksi.
			</div>
		</div>	



		<div style="margin-left: 20px" >

			<form id="pnl_schema3-form">

				<div id="pnl_schema3-tableheader" class="schemasection" title="tabel header transaksi" verifikasinote="tabel header transaksi sesuai skema 2">
					<img src="index.php/asset/etap/client/config/icons/etap-trans1.svg" width="15" height="15" style="margin-right: 5px">
					TABEL HEADER TRANSAKSI
				</div>


				<div class="form_row" style="margin-bottom: 30px">
					<div class="form_label_col" style="border: 0px solid black; vertical-align: top; margin-top: 7px; font-weight:bold">TABLENAME</div>
					<div class="form_input_col" style="border: 0px solid black">
						<input id="pnl_schema3-table1-cbo_tablename" class="easyui-combo" style="width: 400px" mapping="table_id" display="table_name" data-options="editable:false, valueField:'id', textField:'text', prompt:'--PILIH--'">
						<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
					</div>
				</div>


				<div id="pnl_schema3-table1-box_fieldsset" style="display: none">

					<div class="form_row">
						<div class="form_label_col" style="border: 0px solid black; vertical-align: top; margin-top: 7px; font-weight:bold">FIELD_TXID</div>
						<div class="form_input_col" style="border: 0px solid black">
							<input id="pnl_schema3-table1-cbo_field_txid" class="easyui-combo" title="FIELD_TXID" style="width: 400px" mapping="field_id" display="field_name" data-options="editable:false, valueField:'id', textField:'text', prompt:'--PILIH--'">
							<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
						</div>
					</div>			

					<div class="form_row">
						<div class="form_label_col" style="border: 0px solid black; vertical-align: top; margin-top: 7px; font-weight:bold">FIELD_TXDATE</div>
						<div class="form_input_col" style="border: 0px solid black">
							<input id="pnl_schema3-table1-cbo_field_txdate" class="easyui-combo" title="FIELD_TXDATE" style="width: 400px" mapping="field_id" display="field_name" data-options="editable:false, valueField:'id', textField:'text', prompt:'--PILIH--'">
							<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
						</div>
					</div>

					<div class="form_row">
						<div class="form_label_col" style="border: 0px solid black; vertical-align: top; margin-top: 7px; font-weight:bold">FIELD_SERVICECHARGE</div>
						<div class="form_input_col" style="border: 0px solid black">
							<input id="pnl_schema3-cbo_field_txservicecharge" class="easyui-combo" title="FIELD_ITEMTAX" style="width: 400px" mapping="field_id" display="field_name" data-options="editable:false, valueField:'id', textField:'text' ,prompt:'--PILIH--'">
							<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
						</div>
					</div>

					<div class="form_row">
						<div class="form_label_col" style="border: 0px solid black; vertical-align: top; margin-top: 7px; font-weight:bold">FIELD_TXVOID</div>
						<div class="form_input_col" style="border: 0px solid black">
							<input id="pnl_schema3-table1-cbo_field_txisvoid" class="easyui-combo" title="FIELD_TXVOID" style="width: 400px" mapping="field_id" display="field_name" data-options="editable:false, valueField:'id', textField:'text' ,prompt:'--PILIH--'">
							<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
						</div>
					</div>

					<div class="form_row">
						<div class="form_label_col" style="border: 0px solid black; vertical-align: top; margin-top: 7px; font-weight:bold">&nbsp;</div>
						<div class="form_input_col" style="border: 0px solid black">
							<div style="display: flex;">
								<input id="pnl_schema3-table1-chk_schema_isverify" class="easyui-checkbox c1" data-options="label: 'Telah diverifikasi', labelPosition: 'after', checked: false, labelWidth: '115px', disabled: true">
								<a href="javascript:void(0)" id="pnl_schema3-table1-btn_preview" data-options="plain: true, height:'20px', size: 'small'">Preview Data</a>
							</div>
						</div>
					</div>
					
				</div>



				<div id="pnl_schema3-tabledetil" class="schemasection" title="tabel detil item penjualan" verifikasinote="tabel detil item penjualan sesuai skema 3">
					<img src="index.php/asset/etap/client/config/icons/etap-trans2.svg" width="15" height="15" style="margin-right: 5px">
					TABEL DETIL ITEM PENJUALAN
				</div>

				<div class="form_row" style="margin-bottom: 30px">
					<div class="form_label_col" style="border: 0px solid black; vertical-align: top; margin-top: 7px; font-weight:bold">TABLENAME</div>
					<div class="form_input_col" style="border: 0px solid black">
						<input id="pnl_schema3-table2-cbo_tablename" class="easyui-combo" style="width: 400px" mapping="table_id" display="table_name" data-options="editable:false, valueField:'id', textField:'text', prompt:'--PILIH--'">
						<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
					</div>
				</div>


				<div id="pnl_schema3-table2-box_fieldsset" style="display: none">

					<div class="form_row">
						<div class="form_label_col" style="border: 0px solid black; vertical-align: top; margin-top: 7px; font-weight:bold">FIELD_TXID</div>
						<div class="form_input_col" style="border: 0px solid black">
							<input id="pnl_schema3-table2-cbo_field_txid" class="easyui-combo" title="FIELD_TXID" style="width: 400px" mapping="field_id" display="field_name" data-options="editable:false, valueField:'id', textField:'text', prompt:'--PILIH--'">
							<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
						</div>
					</div>	


					<div class="form_row">
						<div class="form_label_col" style="border: 0px solid black; vertical-align: top; margin-top: 7px; font-weight:bold">FIELD_ITEMNAME</div>
						<div class="form_input_col" style="border: 0px solid black">
							<input id="pnl_schema3-table2-cbo_field_itemname" class="easyui-combo" title="FIELD_ITEMNAME" style="width: 400px" mapping="field_id" display="field_name" data-options="editable:false, valueField:'id', textField:'text' ,prompt:'--PILIH--'">
							<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
						</div>
					</div>


					<div class="form_row">
						<div class="form_label_col" style="border: 0px solid black; vertical-align: top; margin-top: 7px; font-weight:bold">FIELD_ITEMQTY</div>
						<div class="form_input_col" style="border: 0px solid black">
							<input id="pnl_schema3-table2-cbo_field_itemqty" class="easyui-combo" title="FIELD_ITEMQTY" style="width: 400px" mapping="field_id" display="field_name" data-options="editable:false, valueField:'id', textField:'text' ,prompt:'--PILIH--'">
							<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
						</div>
					</div>


					<div class="form_row">
						<div class="form_label_col" style="border: 0px solid black; vertical-align: top; margin-top: 7px; font-weight:bold">FIELD_ITEMSUBTOTAL</div>
						<div class="form_input_col" style="border: 0px solid black">
							<input id="pnl_schema3-table2-cbo_field_itemsubtotal" class="easyui-combo" title="FIELD_ITEMSUBTOTAL" style="width: 400px" mapping="field_id" display="field_name" data-options="editable:false, valueField:'id', textField:'text' ,prompt:'--PILIH--'">
							<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
						</div>
					</div>


					<div class="form_row">
						<div class="form_label_col" style="border: 0px solid black; vertical-align: top; margin-top: 7px; font-weight:bold">FIELD_ITEMTAX</div>
						<div class="form_input_col" style="border: 0px solid black">
							<input id="pnl_schema3-table2-cbo_field_itemtax" class="easyui-combo" title="FIELD_ITEMTAX" style="width: 400px" mapping="field_id" display="field_name" data-options="editable:false, valueField:'id', textField:'text' ,prompt:'--PILIH--'">
							<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
						</div>
					</div>

					<div class="form_row">
						<div class="form_label_col" style="border: 0px solid black; vertical-align: top; margin-top: 7px; font-weight:bold">&nbsp;</div>
						<div class="form_input_col" style="border: 0px solid black">
							<div style="display: flex;">
								<input id="pnl_schema3-table2-chk_schema_isverify" class="easyui-checkbox c1" data-options="label: 'Telah diverifikasi', labelPosition: 'after', checked: false, labelWidth: '115px', disabled: true">
								<a href="javascript:void(0)" id="pnl_schema3-table2-btn_preview" data-options="plain: true, height:'20px', size: 'small'">Preview Data</a>
							</div>
						</div>
					</div>


				</div>





				<div id="pnl_schema3-tablepayment" class="schemasection" title="tabel pembayaran penjualan" verifikasinote="tabel pembayaran sesuai skema 3">
					<img src="index.php/asset/etap/client/config/icons/etap-trans3.svg" width="15" height="15" style="margin-right: 5px">
					TABEL PEMBAYARAN
				</div>

				<div class="form_row" style="margin-bottom: 30px">
					<div class="form_label_col" style="border: 0px solid black; vertical-align: top; margin-top: 7px; font-weight:bold">TABLENAME</div>
					<div class="form_input_col" style="border: 0px solid black">
						<input id="pnl_schema3-table3-cbo_tablename" class="easyui-combo" style="width: 400px" mapping="table_id" display="table_name" data-options="editable:false, valueField:'id', textField:'text', prompt:'--PILIH--'">
						<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
					</div>
				</div>


				<div id="pnl_schema3-table3-box_fieldsset" style="display: none">

					<div class="form_row">
						<div class="form_label_col" style="border: 0px solid black; vertical-align: top; margin-top: 7px; font-weight:bold">FIELD_TXID</div>
						<div class="form_input_col" style="border: 0px solid black">
							<input id="pnl_schema3-table3-cbo_field_txid" class="easyui-combo" title="FIELD_TXID" style="width: 400px" mapping="field_id" display="field_name" data-options="editable:false, valueField:'id', textField:'text', prompt:'--PILIH--'">
							<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
						</div>
					</div>	

					<div class="form_row">
						<div class="form_label_col" style="border: 0px solid black; vertical-align: top; margin-top: 7px; font-weight:bold">FIELD_PAYMENTNAME</div>
						<div class="form_input_col" style="border: 0px solid black">
							<input id="pnl_schema3-table3-cbo_field_paymentname" class="easyui-combo" title="FIELD_PAYMENTNAME" style="width: 400px" mapping="field_id" display="field_name" data-options="editable:false, valueField:'id', textField:'text' ,prompt:'--PILIH--'">
							<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
						</div>
					</div>

					<div class="form_row">
						<div class="form_label_col" style="border: 0px solid black; vertical-align: top; margin-top: 7px; font-weight:bold">FIELD_PAYMENTVALUE</div>
						<div class="form_input_col" style="border: 0px solid black">
							<input id="pnl_schema3-table3-cbo_field_paymentvalue" class="easyui-combo" title="FIELD_PAYMENTVALUE" style="width: 400px" mapping="field_id" display="field_name" data-options="editable:false, valueField:'id', textField:'text' ,prompt:'--PILIH--'">
							<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
						</div>
					</div>


					<div class="form_row">
						<div class="form_label_col" style="border: 0px solid black; vertical-align: top; margin-top: 7px; font-weight:bold">&nbsp;</div>
						<div class="form_input_col" style="border: 0px solid black">
							<div style="display: flex;">
								<input id="pnl_schema3-table3-chk_schema_isverify" class="easyui-checkbox c1" data-options="label: 'Telah diverifikasi', labelPosition: 'after', checked: false, labelWidth: '115px', disabled: true">
								<a href="javascript:void(0)" id="pnl_schema3-table3-btn_preview" data-options="plain: true, height:'20px', size: 'small'">Preview Data</a>
							</div>
						</div>
					</div>


				</div>







				<div id="pnl_schema3-box_nextprocess" class="box_nextprocess">

					<!--- BUTTON -->
					<div class="form_row" style="margin-top: 30px">
						<div class="form_label_col"></div>
						<div class="form_input_col" style="border: 0px solid black">
							<a id="pnl_schema3-btn_next" class="easyui-linkbutton c8" style="width">Selanjutnya</a>
						</div>
					</div>	

				</div>

			</form>

			<div class="form_row" style="margin-top: 50px">
			
			</div>

		</div>	
	
	</div>	

</div>	