<div id="pnl_verify" style="display:none">
	<div class="fgta-page-title">Verifikasi Skema</div>
	<div class="namatoko">Nama Toko</div>
	<div class="judulverifikasi" id="pnl_verify-txt_title">Verifikasi</div>



	<form id="pnl_verify-form">

		<div class="form_row" style="margin-bottom: 15px">
			<div class="form_label_col" style="border: 0px solid black; vertical-align: top; margin-top: 7px; font-weight:bold">Limit</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_verify-cbo_limit" class="easyui-combo" style="width: 400px" mapping="limit_id" display="limit_name" data-options="editable:false, valueField:'id', textField:'text', prompt:'--PILIH--'">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" style="margin-bottom: 30px">
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<a id="pnl_verify-btn_load" class="easyui-linkbutton c8" style="width">Load</a>
			</div>
		</div>	



		<div style="margin-top: 10px" id="pnl_verify-box_model_a">
			<table id="pnl_verify-tbl_model_a" paging="true" cellspacing="0" width="100%">
				<thead>
					<tr>
						<th mapping="txid">txid</th>
						<th mapping="txdate">txdate</th>
						<th mapping="txservicecharge">txservicecharge</th>
						<th mapping="txisvoid">txisvoid</th>
					</tr>
					<tr style="background-color: #cccccc; height: 30px">
						<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">TXID</td>
						<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">TXDATE</td>
						<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">TXSERVICECHARGE</td>
						<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">TXISVOID</td>
					</tr>
				</thead>
			</table>
		</div>



		<div style="margin-top: 10px" id="pnl_verify-box_model_b">
			<table id="pnl_verify-tbl_model_b" paging="true" cellspacing="0" width="100%">
				<thead>
					<tr>
						<th mapping="txid">txid</th>
						<th mapping="itemname">itemname</th>
						<th mapping="itemqty" style="text-align: right" formatter="row_format_number">itemqty</th>
						<th mapping="itemsubtotal" style="text-align: right" formatter="row_format_number">itemsubtotal</th>
						<th mapping="itemtax" style="text-align: right" formatter="row_format_number">itemtax</th>
					</tr>
					<tr style="background-color: #cccccc; height: 30px">
						<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">TXID</td>
						<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ITEMNAME</td>
						<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: right">ITEMQTY</td>
						<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: right">ITEMSUBTOTAL</td>
						<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: right">ITEMTAX</td>
					</tr>
				</thead>
			</table>
		</div>


		<div style="margin-top: 10px" id="pnl_verify-box_model_c">
			<table id="pnl_verify-tbl_model_c" paging="true" cellspacing="0" width="100%">
				<thead>
					<tr>
						<th mapping="txid">txid</th>
						<th mapping="paymentname">paymentname</th>
						<th mapping="paymentvalue"  style="text-align: right" formatter="row_format_number">paymentvalue</th>
					</tr>
					<tr style="background-color: #cccccc; height: 30px">
						<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">TXID</td>
						<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">PAYMENTNAME</td>
						<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: right">PAYMENTVALUE</td>
					</tr>
				</thead>
			</table>
		</div>
		

		<div style="margin-top: 10px" id="pnl_verify-box_model_d">
			<table id="pnl_verify-tbl_model_d" paging="true" cellspacing="0" width="100%">
				<thead>
					<tr>
						<th mapping="txid">txid</th>
						<th mapping="txdate">txdate</th>
						<th mapping="txservicecharge">txservicecharge</th>
						<th mapping="txisvoid">txisvoid</th>
						<th mapping="itemname">itemname</th>
						<th mapping="itemqty" style="text-align: right" formatter="row_format_number">itemqty</th>
						<th mapping="itemsubtotal" style="text-align: right" formatter="row_format_number">itemsubtotal</th>
						<th mapping="itemtax" style="text-align: right" formatter="row_format_number">itemtax</th>
					</tr>
					<tr style="background-color: #cccccc; height: 30px">
						<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">TXID</td>
						<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">TXDATE</td>
						<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">TXSERVICECHARGE</td>
						<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">TXISVOID</td>
						<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ITEMNAME</td>
						<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: right">ITEMQTY</td>
						<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: right">ITEMSUBTOTAL</td>
						<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: right">ITEMTAX</td>					
					</tr>
				</thead>
			</table>
		</div>



		<div class="pnl_verify-box_verify">
		<div style="display: flex;">
			<div style="width: 35px; padding-top: 3px">
				<input id="pnl_verify-chk_table_isverify" class="easyui-checkbox c1" data-options="labelPosition: 'after', checked: false">
			</div>
			<div>
				<div style="display: inline-block; font-size: 14px; transform:translateY(1px)">Saya telah melakukan verifikasi tabel di atas,</div>,
				<div>dan memastikan ini adalah benar <span id="pnl_verify-txt_verifynote">tabel transaksi sesuai skema 1</span></div>
			</div>
		</div>
		</div>
	</form>

	<div class="pnl_verify-box_verify">
	<div style="margin-top: 10px; margin-bottom: 10px">
		<a id="pnl_verify-btn_verify" class="easyui-linkbutton c8" style="width">Verify</a>
	</div>
	</div>



</div>	
<!-- END PANEL VERIFY -->


