<?php require_once dirname(__FILE__).'/config-01-selectsite.phtml' ?>
<?php require_once dirname(__FILE__).'/config-02-selectdb.phtml' ?>
<?php require_once dirname(__FILE__).'/config-03-selectmodel.phtml' ?>
<?php require_once dirname(__FILE__).'/config-04a-schema1.phtml' ?>
<?php require_once dirname(__FILE__).'/config-04b-schema2.phtml' ?>
<?php require_once dirname(__FILE__).'/config-04c-schema3.phtml' ?>
<?php require_once dirname(__FILE__).'/config-05-verify.phtml' ?>
<?php require_once dirname(__FILE__).'/config-06-final.phtml' ?>


<?php require_once dirname(__FILE__).'/config-test.phtml' ?>



<div style="display: flex; justify-content: space-between; padding-top: 10px; border-top: 1px solid black">
<div id="obj_panelname">panelname</div>
<a href="javascript:location.reload()">reload</a>
</div>
