<div id="pnl_selectsite">
	<div class="fgta-page-title">Pilih Site</div>
	<div>Berikut adalahh daftar site yang telah di jadwalkan untuk di setup hari ini</div>



	<div style="margin-top: 10px">
		<table id="pnl_selectsite-tbl_list" paging="true" cellspacing="0" width="100%">
			<thead>
				<tr>
					<th mapping="site_id">site_id</th>
					<th mapping="site_name">site_name</th>
					<th mapping="land_name">land_name</th>
					<th mapping="dbtype">dbtype</th>
					<th mapping="taxtype_id">tax</th>
				</tr>
				<tr style="background-color: #cccccc; height: 30px">
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
					<td class="fgtable-head" style="border-bottom: 1px solid #000000">Nama Toko</td>
					<td class="fgtable-head" style="width: 200px; border-bottom: 1px solid #000000">Lokasi</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">DbType</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Tax</td>
				</tr>
			</thead>
		</table>
	</div>


</div>