<div id="pnl_selectdb" style="display:none">
	<div class="fgta-page-title">Konfigurasi Database</div>

	<div class="namatoko">Nama Toko</div>


	<form id="pnl_selectdb-form">

		<div class="form_row">
			<div class="form_label_col" style="border: 0px solid black; vertical-align: top; margin-top: 7px; font-weight:bold">Engine</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_selectdb-cbo_dbtype_id" class="easyui-combo" style="width: 400px" mapping="config_id" display="config_name" data-options="disabled: true, readonly: true, editable:false, valueField:'id', textField:'text'">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;">Type engine database di set saat pendaftaran tenant di pusat.</div>
			</div>
		</div>		


		<div class="form_row" style="margin-top: 40px">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px; font-weight:bold">Host</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_selectdb-txt_dbhost" class="easyui-textbox" mapping="config_dbhost"  maxlength="90" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>		

		<div class="form_row">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px; font-weight:bold">Port</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_selectdb-txt_dbport" class="easyui-numberbox" mapping="config_dbport"  maxlength="90" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px; font-weight:bold">Database</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_selectdb-txt_dbname" class="easyui-textbox" mapping="config_dbname"  maxlength="90" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>


		<div class="form_row">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px; font-weight:bold">Database Schema</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_selectdb-txt_dbschema" class="easyui-textbox" mapping="config_dbname"  maxlength="90" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px; font-weight:bold">Username</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_selectdb-txt_dbuser" class="easyui-textbox" mapping="config_dbuser"  maxlength="90" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px; font-weight:bold">Password</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_selectdb-txt_dbpassword" class="easyui-passwordbox" mapping="config_dbpassword"  maxlength="90" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>



		
	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<a id="pnl_selectdb-btn_next" class="easyui-linkbutton c8" style="width">Selanjutnya</a>
		</div>
	</div>	


	<div class="form_row" style="margin-top: 50px">
	</div>


</div>