<div id="pnl_schema1" style="display:none; flex-direction: column; align-items: flex-start">
	<div class="fgta-page-title">Konfigurasi Skema</div>
	<div class="namatoko">Nama Toko</div>


	<div style="display: flex">
		<div style="width: 140px; text-align: center">
			<div><img name="pnl_selectmodel-schema" schemaname="schema1" src="index.php/asset/etap/client/config/icons/schema1.svg" width="140" height="140" style="cursor: pointer"></div>
			<div style="position: relative; top: -50px; text-align: center; font-weight: bold">Skema 1</div>
			<div style="position: relative; top: -40px">
			Single table untuk menyimpan seluruh item dalam satu transaksi. 
			Pada tipe ini hanya menggunakan satu macam pembayaran.
			</div>
		</div>	



		<div >

			<form id="pnl_schema1-form">

				<div id="pnl_schema1-tabledata" class="schemasection" title="tabel transaksi" verifikasinote="tabel transaksi sesuai skema 1">
					<img src="index.php/asset/etap/client/config/icons/etap-trans1.svg" width="15" height="15" style="margin-right: 5px">
					TABEL TRANSAKSI
				</div>


				<div class="form_row" style="margin-bottom: 30px">
					<div class="form_label_col" style="border: 0px solid black; vertical-align: top; margin-top: 7px; font-weight:bold">TABLENAME</div>
					<div class="form_input_col" style="border: 0px solid black">
						<input id="pnl_schema1-cbo_tablename" class="easyui-combo" style="width: 400px" mapping="table_id" display="table_name" data-options="editable:false, valueField:'id', textField:'text', prompt:'--PILIH--'">
						<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
					</div>
				</div>


				<div id="pnl_schema1-box_fieldsset" style="display: none">


					<div class="form_row">
						<div class="form_label_col" style="border: 0px solid black; vertical-align: top; margin-top: 7px; font-weight:bold">FIELD_TXID</div>
						<div class="form_input_col" style="border: 0px solid black">
							<input id="pnl_schema1-cbo_field_txid" class="easyui-combo" title="FIELD_TXID" style="width: 400px" mapping="field_id" display="field_name" data-options="editable:false, valueField:'id', textField:'text', prompt:'--PILIH--'">
							<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
						</div>
					</div>			

					<div class="form_row">
						<div class="form_label_col" style="border: 0px solid black; vertical-align: top; margin-top: 7px; font-weight:bold">FIELD_TXDATE</div>
						<div class="form_input_col" style="border: 0px solid black">
							<input id="pnl_schema1-cbo_field_txdate" class="easyui-combo" title="FIELD_TXDATE" style="width: 400px" mapping="field_id" display="field_name" data-options="editable:false, valueField:'id', textField:'text', prompt:'--PILIH--'">
							<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
						</div>
					</div>
					
					<div class="form_row">
						<div class="form_label_col" style="border: 0px solid black; vertical-align: top; margin-top: 7px; font-weight:bold">FIELD_SERVICECHARGE</div>
						<div class="form_input_col" style="border: 0px solid black">
							<input id="pnl_schema1-cbo_field_txservicecharge" class="easyui-combo" title="FIELD_ITEMTAX" style="width: 400px" mapping="field_id" display="field_name" data-options="editable:false, valueField:'id', textField:'text' ,prompt:'--PILIH--'">
							<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
						</div>
					</div>

					<div class="form_row">
						<div class="form_label_col" style="border: 0px solid black; vertical-align: top; margin-top: 7px; font-weight:bold">FIELD_TXVOID</div>
						<div class="form_input_col" style="border: 0px solid black">
							<input id="pnl_schema1-cbo_field_txisvoid" class="easyui-combo" title="FIELD_TXVOID" style="width: 400px" mapping="field_id" display="field_name" data-options="editable:false, valueField:'id', textField:'text' ,prompt:'--PILIH--'">
							<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
						</div>
					</div>

					<div class="form_row">
						<div class="form_label_col" style="border: 0px solid black; vertical-align: top; margin-top: 7px; font-weight:bold">FIELD_ITEMNAME</div>
						<div class="form_input_col" style="border: 0px solid black">
							<input id="pnl_schema1-cbo_field_itemname" class="easyui-combo" title="FIELD_ITEMNAME" style="width: 400px" mapping="field_id" display="field_name" data-options="editable:false, valueField:'id', textField:'text' ,prompt:'--PILIH--'">
							<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
						</div>
					</div>


					<div class="form_row">
						<div class="form_label_col" style="border: 0px solid black; vertical-align: top; margin-top: 7px; font-weight:bold">FIELD_ITEMQTY</div>
						<div class="form_input_col" style="border: 0px solid black">
							<input id="pnl_schema1-cbo_field_itemqty" class="easyui-combo" title="FIELD_ITEMQTY" style="width: 400px" mapping="field_id" display="field_name" data-options="editable:false, valueField:'id', textField:'text' ,prompt:'--PILIH--'">
							<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
						</div>
					</div>


					<div class="form_row">
						<div class="form_label_col" style="border: 0px solid black; vertical-align: top; margin-top: 7px; font-weight:bold">FIELD_ITEMSUBTOTAL</div>
						<div class="form_input_col" style="border: 0px solid black">
							<input id="pnl_schema1-cbo_field_itemsubtotal" class="easyui-combo" title="FIELD_ITEMSUBTOTAL" style="width: 400px" mapping="field_id" display="field_name" data-options="editable:false, valueField:'id', textField:'text' ,prompt:'--PILIH--'">
							<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
						</div>
					</div>


					<div class="form_row">
						<div class="form_label_col" style="border: 0px solid black; vertical-align: top; margin-top: 7px; font-weight:bold">FIELD_ITEMTAX</div>
						<div class="form_input_col" style="border: 0px solid black">
							<input id="pnl_schema1-cbo_field_itemtax" class="easyui-combo" title="FIELD_ITEMTAX" style="width: 400px" mapping="field_id" display="field_name" data-options="editable:false, valueField:'id', textField:'text' ,prompt:'--PILIH--'">
							<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
						</div>
					</div>



					<div class="form_row">
						<div class="form_label_col" style="border: 0px solid black; vertical-align: top; margin-top: 7px; font-weight:bold">&nbsp;</div>
						<div class="form_input_col" style="border: 0px solid black">
							<div style="display: flex;">
								<input id="pnl_schema1-chk_schema_isverify" class="easyui-checkbox c1" data-options="label: 'Telah diverifikasi', labelPosition: 'after', checked: false, labelWidth: '115px', disabled: true">
								<a href="javascript:void(0)" id="pnl_schema1-btn_preview" data-options="plain: true, height:'20px', size: 'small'">Preview Data</a>
							</div>
						</div>
					</div>

					
				</div>



				<div id="pnl_schema1-box_nextprocess" class="box_nextprocess">

					<!--- BUTTON -->
					<div class="form_row" style="margin-top: 30px">
						<div class="form_label_col"></div>
						<div class="form_input_col" style="border: 0px solid black">
							<a id="pnl_schema1-btn_next" class="easyui-linkbutton c8" style="width">Selanjutnya</a>
						</div>
					</div>	

				</div>


			</form>

			<div class="form_row" style="margin-top: 50px">
			</div>

		</div>	
	
	</div>	

</div>	