

<div id="pnl_final" style="display:none">
	<div class="fgta-page-title">Finalisasi</div>
	<div class="namatoko">Nama Toko</div>


	<form id="pnl_final-form">


		<div class="form_row">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Mulai Tanggal</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_final-dt_datestart" class="easyui-datebox" style="width: 100px" mapping="dt_datestart" data-options="editable:false ">
				<a id="pnl_final-btn_test" class="easyui-linkbutton c8" style="width">Run</a>
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_final-chk_view_response" class="easyui-checkbox c1" mapping="view_response" data-options="label: 'View Response', labelPosition: 'after', labelWidth: '200px', checked: false">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_final-chk_view_data" class="easyui-checkbox c1" mapping="view_data" data-options="label: 'View Data', labelPosition: 'after', labelWidth: '200px', checked: false ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">&nbsp;</div>
			<div class="form_input_col" style="border: 0px solid black">
				<div style="font-weight: bold">Result:</div>
				<div id="pnl_final-txt_result" style="height: 400px; overflow: scroll; border: 1px solid #ccc; background-color: #00000015">
					&nbsp;
				</div>
			</div>
		</div>		

	</form>

	<div id="pnl_final-box_finish" class="form_row" style="margin-top: 30px; margin-bottom 50px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<div style="padding: 10px; border-color: 2px solid brown; background-color: #c7a373; margin-bottom: 30px; color: #251908">
				<div style="font-weight: bold; margin-bottom: 5px">PERHATIAN!!</div>
				Jangan lupa untuk install service pengiriman data otomatis (<b><i>as administrator</i></b>).
			</div>
			<a id="pnl_final-btn_finish" class="easyui-linkbutton c8" style="width">Selesai</a>
		</div>
	</div>	

	<div>&nbsp;</div>


</div>