<div id="pnl_main">


	<div id="pnl_main-task">
		<div class="task-progress">
			<div class="easyui-progressbar task-progress-status" data-options="value:60"></div>
			<div class="task-progress-text" style="margin-top: 5px; margin-bottom: 10px">
				text progress
			</div>
		</div>
		<a class="easyui-linkbutton task-start" style="outline: none;" href="javascript:void(0)">Sync TB</a>
		<a class="easyui-linkbutton task-cancel" style="outline: none;" href="javascript:void(0)">Cancel</a>
	</div>


</div>